version: '3.1'

services:
  db:
    image: mysql
    networks: 
      - alpha
    command: --default-authentication-plugin=mysql_native_password
    restart: always
#    secrets:
#      - db_root_password
#      - db_dba_password
    environment:
      MYSQL_USER: dba
      MYSQL_DATABASE: beaverdb
# these need to be replaced with secrets in production
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_PASSWOED: dbapwd
#      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
#      MYSQL_PASSWORD_FILE: /run/secrets/db_dba_password
 
  adminer:
    image: adminer
    networks: 
      - alpha
    restart: always
    ports: 
      - '0.0.0.0:8080:8080'

  api:
    image: chrskllr/booking-beaver-api
    depends_on:
      - "db"
    command: ["-c", "/app/wait-for.sh db:3306 && /app/run.sh start"]
    entrypoint: ["/bin/sh"]
    networks: 
      - alpha
    build:
      context: api
    ports: 
      - '0.0.0.0:7500:7500'

  ui:
    image: chrskllr/booking-beaver-ui
    depends_on:
      - api
    networks: 
      - alpha
    build:
      context: ui
    ports: 
      - '0.0.0.0:3000:3000'

#secrets:
#  db_root_password:
#    external: true
#  db_dba_password:
#    external: true


networks: 
  alpha:
